server:
   port: 8761
spring:
    application:
        name: sms-eureka
eureka:
    server:
        enable-self-preservation: false
        responseCacheUpdateInvervalMs: 10000
        responseCacheAutoExpirationInSeconds: 60
        eviction-interval-timer-in-ms: 10000
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
           defaultZone: http://127.0.0.1:${server.port}/eureka/