server:
   port: 8762
spring:
    application:
        name: sms-eureka  
eureka:
    #server:
    #    enable-self-preservation: true
    #    responseCacheUpdateInvervalMs: 10000
    #    responseCacheAutoExpirationInSeconds: 60
    #    eviction-interval-timer-in-ms: 10000
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
           defaultZone: http://172.18.201.75:8761/eureka/
            