
server:
   port: 8761
spring:
    application:
        name: bbt-eureka   
eureka:
    server:
        enable-self-preservation: false
        responseCacheUpdateInvervalMs: 3000
        responseCacheAutoExpirationInSeconds: 60
        eviction-interval-timer-in-ms: 3000
    instance:
        preferIpAddress: true
        instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://10.116.210.141:8761/eureka/
            