server:
   port: 8761
spring:
    application:
        name: sms-eureka
eureka:
    server:
        enable-self-preservation: false
        responseCacheUpdateInvervalMs: 20000
        responseCacheAutoExpirationInSeconds: 60
        eviction-interval-timer-in-ms: 20000
    instance:
        preferIpAddress: true
        instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
           defaultZone: http://118.31.8.202:${server.port}/eureka/
