
server:
   port: 8761
spring:
    application:
        name: sms-eureka
eureka:
    server:
        enable-self-preservation: false
        responseCacheUpdateInvervalMs: 3000
        responseCacheAutoExpirationInSeconds: 60
        eviction-interval-timer-in-ms: 3000
    instance:
        preferIpAddress: true
        instance-id: 172.18.201.75:sms-eureka:8761
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://172.18.201.75:8761/eureka/
            