
server:
   port: 8761
spring:
    application:
        name: sms-eureka
eureka:
    server:
        enable-self-preservation: false
        responseCacheUpdateInvervalMs: 3000
        responseCacheAutoExpirationInSeconds: 60
        eviction-interval-timer-in-ms: 3000
   