server:
   port: 8761
spring:
    application:
        name: sms-eureka
eureka:
    server:
        enable-self-preservation: false
        responseCacheUpdateInvervalMs: 20000
        responseCacheAutoExpirationInSeconds: 60
        eviction-interval-timer-in-ms: 20000
    instance:
        hostname: peer1
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
           defaultZone: http://peer2:${server.port}/eureka/
