server:
   port: 8761
spring:
    application:
        name: sms-eureka
eureka:
    #server:
    #    enable-self-preservation: true
    #    responseCacheUpdateInvervalMs: 10000
    #    responseCacheAutoExpirationInSeconds: 60
    #    eviction-interval-timer-in-ms: 10000
    instance:
        hostname: peer1
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
           defaultZone: http://peer2:8762/eureka/
