spring:
  application:
      name: sms-eureka

server:
   port: 8761
   
eureka:
    server:
        enable-self-preservation: false
        responseCacheUpdateInvervalMs: 3000
        responseCacheAutoExpirationInSeconds: 60
        eviction-interval-timer-in-ms: 3000
    instance:
        preferIpAddress: true
        instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    client:
        registerWithEureka: true   #表示是否将自己注册到Eureka Server，默认为true。
        fetchRegistry: true  #表示是否从Eureka Server获取注册信息，默认为true。
        serviceUrl:
           defaultZone: http://local:${server.port}/eureka/